### ISSUE TITLE
Machines break down as they're being fixed

### ISSUE THREAD

**Issue by averyfukawa** [Jelled1st/Project_ShowOff#20]
despite them being on a "break on a range of x to y seconds" they break almost always very close together, so the randomness there feels very off
like, i don't know what is going on, but i'm literally fixing them, the sfx for fixing them plays, but a second later the sfx for "it broke down" plays

i feel like after fixing them, the machines should maybe get an immunity timer perhaps, idk. regardless, bc of the machines breaking down it feels more like a game about fixing machines than about getting the potatoes to the theoretical finish line

(Copied from discord)

**Comment by averyfukawa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Factory Behaviour](https://trello.com/c/epv0YkJa/103-factory-behaviour)

**Comment by Hlibix** [comment]
f98bccbde7c370ec3faa1d64498c2b4a415db98f
