### ISSUE TITLE
Stage Changer is breaking the factory level

### ISSUE THREAD

**Issue by averyfukawa** [Jelled1st/Project_ShowOff#22]
With the implementation of a Main Menu, and a shift of all levels by +1, the stage changer is now completely broken, which in turn breaks the factory level.

`case GameStages.Farm / Household` don't exist, meaning those throw your own exception.
With the new changes, the only case that is implemented and works, is the Factory one, and that one sends you to the !Farm Level.

As such, Farm -> Factory, either breaks the game, or you need to disable Stage Changer, or if you set it up according to the inspector qualities, it sends you back to the farm level.

**Comment by averyfukawa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Factory Behaviour](https://trello.com/c/epv0YkJa/103-factory-behaviour)

**Comment by Hlibix** [comment]
3a18dee777c889ac5a5eb6b52e6a8ce812247c3a
5f45201fe5ba1eb1c35fbf7730ee25516ea9fe7e
