### ISSUE TITLE
Can't access level 2 in the factory. Getting the right amount of potatoes does not trigger it.

### ISSUE THREAD

**Issue by iVendrix** [Jelled1st/Project_ShowOff#28]
Getting an error; Factory.FactoryUiManager.SetPotatoesCount (System.Int32 collected, System.Int32 of) (at Assets/Scripts/Factory/FactoryUiManager.cs:31)

**Comment by Hlibix** [comment]
b5a308913ea6ab697a8d97a63214801d2e28f59d
