### ISSUE TITLE
Machines in second factory level can breakdown and smoke before the player gets there

### ISSUE THREAD

**Issue by tali055** [Jelled1st/Project_ShowOff#35]

**Comment by averyfukawa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Machines from level 2 are "breaking down" despite being in level 1](https://trello.com/c/x3M9hsND/197-bug-machines-from-level-2-are-breaking-down-despite-being-in-level-1)

**Comment by Hlibix** [comment]
d09e129b126bf701057577015fcd9d824b04dbe0
