### ISSUE TITLE
Be able to cut by swiping up or down

### ISSUE THREAD

**Issue by averyfukawa** [Jelled1st/Project_ShowOff#38]

**Comment by averyfukawa** [comment]
Currently you can cut with the knife only by swiping upwards, rarely sideways, therefore, make it able to do both so the knife feels less finicky.

**Comment by averyfukawa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enhancement: Be able to cut by swiping UP or DOWN](https://trello.com/c/QPEeDpwB/196-enhancement-be-able-to-cut-by-swiping-up-or-down)

**Comment by Jelled1st** [comment]
Done
