### ISSUE TITLE
A few of the OnEventPlayer events aren't working for playing the audio

### ISSUE THREAD

**Issue by averyfukawa** [Jelled1st/Project_ShowOff#39]
> On Baking start does not play the audio of SoundSearing
> On Baking Burnt does not play the audio of SoundBurning
> On Fryer Start does not play the audio of SoundFryFrying
> On Fryer Stop does not play the audio of SoundFriesDone
> On Baking Done, On Cooking Done, does not play the audio

So far, only "On Cut Cuttable Soft" and "On Cut Cuttable Hard" seem to work.

And yes, the 3 dishes were assigned under dishes, the game handler has been assigned, and the touch controller has been assigned.

> The On Finish event also doesn't seem to be the one running when the "Score UI" GameObject gets enabled, meaning the StopMusicFade function does not happen.

**Comment by averyfukawa** [comment]
> On Burnt does not work on 1 side, or on 2 sides fully burnt
> On Finish is not calling the event

**Comment by averyfukawa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: On burnt & On Finish not calling events correctly of the "OnEventPlayer"](https://trello.com/c/QZVX3PI5/195-bug-on-burnt-on-finish-not-calling-events-correctly-of-the-oneventplayer)

**Comment by Jelled1st** [comment]
The kitchen game handler was checking if an observer is a game handler observer, however it was checking if the array was a game handler observer, checking array[index] solved the issue
