### ISSUE TITLE
Dragging the spoon from the pot created a massive list invisible spoon clonses

### ISSUE THREAD

**Issue by averyfukawa** [Jelled1st/Project_ShowOff#40]

**Comment by averyfukawa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Dragging spoon to environment creates a bunch of invisible copies](https://trello.com/c/IBPJHAiV/194-bug-dragging-spoon-to-environment-creates-a-bunch-of-invisible-copies)

**Comment by Jelled1st** [comment]
When fixing this bug I also found two other bugs (possible caused by a chance in code) which did drop all the food in the cookingpan onto the dish. I fixed both issues
