### ISSUE TITLE
Game Manager script warnings

### ISSUE THREAD

**Issue by tali055** [Jelled1st/Project_ShowOff#6]
![image](https://user-images.githubusercontent.com/37297785/81667637-ccec9d80-9443-11ea-904d-6f7a01248711.png)

let's try and resolve these when there's time to keep things clean

**Comment by Hlibix** [comment]
Same as #5 is a Unity bug
https://issuetracker.unity3d.com/issues/serializedfield-fields-produce-field-is-never-assigned-to-dot-dot-dot-warning

**Comment by Jelled1st** [comment]
Unity gives those warnings on [SerializeField]'s because the values are never set in code, but through editor
