### ISSUE TITLE
Performance Bug on Farm

### ISSUE THREAD

**Issue by averyfukawa** [Jelled1st/Project_ShowOff#8]
I was dragging a potato plot to the truck a little too slow so the "click" feedback was still playing as i dragged it, then when it reached the truck my assumption is the raycast was confused whether the truck or the potato layer was the one it was supposed to shoot rays to

then Unity Crashed alongside my wallpaper engine, chrome, and all my other things :x

**Comment by averyfukawa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Farm game mechanics](https://trello.com/c/auvyt5gW/65-farm-game-mechanics)

**Comment by Jelled1st** [comment]
Disable the FPSDebug (in Jelle Tests scene attached to camera) and the issue should be resolved.
