### ISSUE TITLE
Replanting Bug

### ISSUE THREAD

**Issue by averyfukawa** [Jelled1st/Project_ShowOff#9]
Replanting on a plot you previously harvested removes the mounds of light brown dirt completely

**Comment by averyfukawa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Farm game mechanics](https://trello.com/c/auvyt5gW/65-farm-game-mechanics)

**Comment by Jelled1st** [comment]
There was no bug. Dirt mound was removed for visual cue that digging was necesarry.
